version: "2"

linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - wrapcheck
    - tagalign
    - forbidigo
    - perfsprint
    - gochecknoglobals
    - wsl  # deprecated
    - revive  # too noisy
    # Legacy code suppressions:
    - cyclop
    - err113
    - errcheck
    - ireturn
    - lll
    - mnd
    - modernize
    - noinlineerr
    - prealloc
    - staticcheck
    - tagliatelle
    - varnamelen
    - whitespace
    - wsl_v5
    - gosec
